'use client'

import { useState } from 'react'

export default function RetrospectivePage() {
  const [retro, setRetro] = useState<string | null>(null)
  const [loading, setLoading] = useState(false)
  const [provider, setProvider] = useState<string | null>(null)

  async function generate() {
    setLoading(true)
    setRetro(null)
    try {
      const res = await fetch('/api/ai/retrospective', { method: 'POST' })
      const data = await res.json()
      if (data.error) {
        setRetro(`Error: ${data.error}`)
      } else {
        setRetro(data.retrospective)
        setProvider(data.provider)
      }
    } catch {
      setRetro('Failed to generate. Please try again.')
    }
    setLoading(false)
  }

  return (
    <div className="p-8">
      <div className="mb-8">
        <h1 className="text-xl font-semibold tracking-tight">AI Retrospective</h1>
        <p className="text-gray-500 text-sm mt-0.5">AI-written sprint summary from your metrics</p>
      </div>

      <div className="max-w-2xl">
        <div className="bg-white/[0.02] border border-white/[0.06] rounded-xl p-6 mb-4">
          <p className="text-gray-400 text-sm mb-5">
            Generates a sprint retrospective based on your PR cycle times, deployment frequency, and failure rates — referencing your actual numbers.
          </p>
          <button
            onClick={generate}
            disabled={loading}
            className="flex items-center gap-2 bg-blue-600 hover:bg-blue-500 disabled:bg-blue-900 disabled:text-blue-600 text-white text-sm font-medium px-5 py-2.5 rounded-lg transition"
          >
            <span>{loading ? '⟳' : '✦'}</span>
            {loading ? 'Generating...' : 'Generate Retrospective'}
          </button>
        </div>

        {retro && (
          <div className="bg-white/[0.02] border border-white/[0.06] rounded-xl p-6">
            {provider && (
              <div className="flex items-center gap-2 mb-5 pb-4 border-b border-white/[0.06]">
                <span className="text-xs text-gray-600">Generated by</span>
                <span className="text-xs bg-white/[0.05] text-gray-400 px-2 py-0.5 rounded-full capitalize">{provider}</span>
              </div>
            )}
            <div className="space-y-1">
              {retro.split('\n').map((line, i) => {
                if (line.startsWith('### ') || line.startsWith('## ')) {
                  return <h3 key={i} className="text-sm font-semibold text-white mt-5 mb-2">{line.replace(/#{2,3} /, '')}</h3>
                }
                if (line.startsWith('* ') || line.startsWith('- ')) {
                  return <p key={i} className="text-sm text-gray-400 pl-4 before:content-['·'] before:mr-2 before:text-gray-600">{line.slice(2)}</p>
                }
                if (line.startsWith('**') && line.endsWith('**')) {
                  return <h3 key={i} className="text-sm font-semibold text-white mt-5 mb-2">{line.replace(/\*\*/g, '')}</h3>
                }
                if (line.trim() === '') return null
                return <p key={i} className="text-sm text-gray-400">{line}</p>
              })}
            </div>
          </div>
        )}
      </div>
    </div>
  )
}