'use client'

import { useState } from 'react'
import Link from 'next/link'

export default function RetrospectivePage() {
  const [retro, setRetro] = useState<string | null>(null)
  const [loading, setLoading] = useState(false)

  async function generate() {
    setLoading(true)
    const res = await fetch('/api/ai/retrospective', { method: 'POST' })
    const data = await res.json()
    setRetro(data.retrospective + `\n\n---\n*Generated by ${data.provider}*`)
    setLoading(false)
  }

  return (
    <div className="min-h-screen bg-gray-950 text-white p-8">
      <div className="max-w-3xl mx-auto">

        <div className="flex items-center gap-4 mb-8">
          <Link href="/dashboard" className="text-gray-400 hover:text-white transition">← Back</Link>
          <h1 className="text-2xl font-bold">AI Sprint Retrospective</h1>
        </div>

        <div className="bg-gray-900 border border-gray-800 rounded-xl p-8 mb-6">
          <p className="text-gray-400 mb-6">
            Generate an AI-written retrospective based on your team's actual metrics — PR cycle times, deployment frequency, and failure rates.
          </p>
          <button
            onClick={generate}
            disabled={loading}
            className="bg-blue-600 hover:bg-blue-700 disabled:bg-blue-900 disabled:text-blue-400 text-white font-semibold px-6 py-3 rounded-lg transition"
          >
            {loading ? '✨ Generating...' : '✨ Generate Retrospective'}
          </button>
        </div>

        {retro && (
          <div className="bg-gray-900 border border-gray-800 rounded-xl p-8">
            <div className="prose prose-invert max-w-none">
              {retro.split('\n').map((line, i) => {
                if (line.startsWith('## ') || line.startsWith('**') && line.endsWith('**')) {
                  return <h3 key={i} className="text-lg font-bold text-white mt-6 mb-3">{line.replace(/\*\*/g, '').replace('## ', '')}</h3>
                }
                if (line.startsWith('- ') || line.startsWith('• ')) {
                  return <p key={i} className="text-gray-300 mb-2 pl-4">• {line.slice(2)}</p>
                }
                if (line.startsWith('1.') || line.startsWith('2.') || line.startsWith('3.')) {
                  return <p key={i} className="text-gray-300 mb-2 pl-4">{line}</p>
                }
                if (line.trim() === '') return <br key={i} />
                return <p key={i} className="text-gray-300 mb-2">{line}</p>
              })}
            </div>
          </div>
        )}

      </div>
    </div>
  )
}